## GENERATED BY GEMINI on 10/1/26.
## Command descriptions edited by me.

# Disable default file completion when completing subcommands
complete -c pac -f

# Subcommand definitions
complete -c pac -n "__fish_use_subcommand" -a "install i" -d "Install package(s)"
complete -c pac -n "__fish_use_subcommand" -a "uninstall r" -d "Remove package(s) and their dependencies"
complete -c pac -n "__fish_use_subcommand" -a "update" -d "Refresh package repositories"
complete -c pac -n "__fish_use_subcommand" -a "list" -d "List installed packages"
complete -c pac -n "__fish_use_subcommand" -a "info" -d "Display information about a package"
complete -c pac -n "__fish_use_subcommand" -a "prune" -d "Remove orphan packages"
complete -c pac -n "__fish_use_subcommand" -a "search" -d "Search for a package"
complete -c pac -n "__fish_use_subcommand" -a "browse" -d "Interactively browse and install packages"

# Argument completion: suggest installable repository packages
complete -c pac -n "__fish_seen_subcommand_from install i info search" -a "(pacman -Slq)" -f

# Argument completion: suggest installed local packages
complete -c pac -n "__fish_seen_subcommand_from uninstall r list" -a "(pacman -Qq)" -f
